
import { Roboto } from 'next/font/google'
import "./globals.css";
import Header from './components/layout/Header';


const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700', '900'] })

export const metadata = {
  title: "Portifólio Lucas Barragana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={roboto.className}>
        <main >
          <Header />
        {children}
      
        <footer className="border-t p-8 text-center text-gray-500 mt-16">
                &copy; 2023 All rights reserved - Dev. Lucas Oliveira Barragana
              </footer>
        </main>
      </body>
    </html>
  );
}
